import { NextResponse } from 'next/server';

// This manifest needs to be signed with your Farcaster account
// Visit https://farcaster.xyz/~/settings/developer-tools and use the "Create Manifest" tool
// to generate a properly signed manifest for your domain

export async function GET() {
  // TODO: Replace with your actual signed manifest
  // You need to:
  // 1. Enable Developer Mode in Farcaster
  // 2. Go to https://farcaster.xyz/~/settings/developer-tools
  // 3. Use "Create Manifest" tool
  // 4. Enter your domain: homiehouse.xyz
  // 5. Copy the generated manifest and replace this placeholder
  
  const manifest = {
    accountAssociation: {
      // These will be generated by Farcaster's manifest creation tool
      // based on your FID and domain
      header: "REPLACE_WITH_GENERATED_HEADER",
      payload: "REPLACE_WITH_GENERATED_PAYLOAD",
      signature: "REPLACE_WITH_GENERATED_SIGNATURE"
    },
    frame: {
      version: "1",
      name: "Ask Homie",
      iconUrl: "https://homiehouse.xyz/icon-512.png",
      homeUrl: "https://homiehouse.xyz/mini/ask-homie",
      imageUrl: "https://homiehouse.xyz/og-ask-homie.png",
      buttonTitle: "Ask Homie",
      splashImageUrl: "https://homiehouse.xyz/og-ask-homie.png",
      splashBackgroundColor: "#8B5CF6"
    }
  };

  return NextResponse.json(manifest, {
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
